name: challange
on: push
env:
  ARTIFACT_NAME: myartifact
  
jobs:
    job1: 
        name: job1
        runs-on: ubuntu-latest
        steps:
        - name: step1 checkout
          uses: actions/checkout@v2
        
    job2:
        name: job2
        runs-on: ubuntu-latest
        steps: 
        - name: step2 load artefact
          uses: actions/upload-artifact@v2.0.0
          with:
            name: ${{ env.ARTIFACT_NAME }}
            path: .
        
        
