name: challange
on: push
env:
  ARTIFACT_NAME: myartifact
jobs:
  job1: 
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create artifact file
        run: echo "This is my artifact" > artifact.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: artifact.txt

  job2:
    name: job2
    runs-on: ubuntu-latest
    needs: job1  # <-- Make job2 wait for job1 to finish
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Show artifact content
        run: cat artifact.txt

 
        
        
