name: pythonworkflow
on: workflow_dispatch

jobs:

  data_pipeline:
    name: data_pipeline
    runs-on: ubuntu-latest
    steps:
    - name: clean_data
      run: |
        pwd
        ls -l
        cd ModelCleaning
        echo "this is ModelCleaning folder"
        ls -l



