name: tutorial1
on: push

jobs:
    job1:
         name: job1
         runs-on: ubuntu-latest
         steps:
         run: echo "Hello from job1"
    job2:
         name: job2
         runs-on: windows-latest
         steps: 
         run: echo " hellow from job 2"
    job3:
         
         runs-on: macos
         steps:
         run: echo " hellow from job 3" 
    job4:
         runs-on: ubuntu-latest
         needs: [job1, job2, job3]
         steps:
         run: echo "hello from job 4"